add eval info to bench json

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -4,9 +4,7 @@ on:
   push:
     branches:
       - main
-      - test
-      - compare_to_trend
-      - testIfItStillAintWork
+      - refactor_bench_summary
 
 jobs:
   test:
@@ -15,17 +13,17 @@ jobs:
       - name: checkout the main branch
         uses: actions/checkout@v3
 
-#      - name: checkout the bench_data branch to a given folder
-#        uses: actions/checkout@v3
-#        with:
-#          ref: 'bench_data'
-#          sparse-checkout: |
-#            data.json
-#          sparse-checkout-cone-mode: false
-#          path: 'benchmark_data'
+      - name: checkout the bench_data branch to a given folder
+        uses: actions/checkout@v3
+        with:
+          ref: 'bench_data'
+          sparse-checkout: |
+            data.json
+          sparse-checkout-cone-mode: false
+          path: 'benchmark_data'
 
-#      - name: print the content of the file from the bench_data branch
-#        run: cat benchmark_data/data.json
+      - name: print the content of the file from the bench_data branch
+        run: cat benchmark_data/data.json
 
       - name: evaluate benchmark
         uses: ./
@@ -40,25 +38,25 @@ jobs:
           trend_thresholds: 5,5,5
           failing_condition: none
           add_comment_to_commit: false
-          save_curr_bench_res: false
+          save_curr_bench_res: true
           github_token: ${{ secrets.GH_TOKEN }}
 
-#      - name: print the content of the data file after the update
-#        run: cat benchmark_data/data.json
-#
-#      - name: Commit files
-#        working-directory: ./benchmark_data
-#        run: |
-#          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
-#          git config --local user.name "github-actions[bot]"
-#          git commit -a -m "Add changes"
-#          git push origin bench_data
-#
-#      - name: Check output and fail if needed
-#        if: steps.eval.outputs.should_fail == 'true'
-#        run: |
-#          echo "Failing as indicated by evaluation action"
-#          exit 1
+      - name: print the content of the data file after the update
+        run: cat benchmark_data/data.json
+
+      - name: Commit files
+        working-directory: ./benchmark_data
+        run: |
+          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          git config --local user.name "github-actions[bot]"
+          git commit -a -m "Add changes"
+          git push origin bench_data
+
+      - name: Check output and fail if needed
+        if: steps.eval.outputs.should_fail == 'true'
+        run: |
+          echo "Failing as indicated by evaluation action"
+          exit 1
           
           
 
